spring.datasource.url=jdbc:sqlite:iniflex.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.main.banner-mode=off
# Exibir SQL no console (desabilitado para saída mais limpa)
spring.jpa.show-sql=false
server.port=8081